export const ubications = [
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "LA VICTORIA"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "SAÑIA"},
  { departamento:"LAMBAYEQUE", provincia: "FERREÑAFE", distrito: "CAÑARIS"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "PATAPO"},
  { departamento:"LAMBAYEQUE", provincia: "FERREÑAFE", distrito: "MANUEL ANTONIO MESONES MURO"},
  { departamento:"LAMBAYEQUE", provincia: "LAMBAYEQUE", distrito: "CHOCHOPE"},
  { departamento:"LAMBAYEQUE", provincia: "LAMBAYEQUE", distrito: "MORROPE"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "REQUE"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "LAGUNAS"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "MONSEFU"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "CAYALTI"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "ETEN PUERTO"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "JOSE LEONARDO ORTIZ"},
  { departamento:"LAMBAYEQUE", provincia: "FERREÑAFE", distrito: "INCAHUASI"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "PICSI"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "PIMENTEL"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "POMALCA"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "PUCALA"},
  { departamento:"LAMBAYEQUE", provincia: "FERREÑAFE", distrito: "FERREÑAFE"},
  { departamento:"LAMBAYEQUE", provincia: "FERREÑAFE", distrito: "PUEBLO NUEVO"},
  { departamento:"LAMBAYEQUE", provincia: "LAMBAYEQUE", distrito: "LAMBAYEQUE"},
  { departamento:"LAMBAYEQUE", provincia: "LAMBAYEQUE", distrito: "MOCHUMI"},
  { departamento:"LAMBAYEQUE", provincia: "LAMBAYEQUE", distrito: "SAN JOSE"},
  { departamento:"LAMBAYEQUE", provincia: "LAMBAYEQUE", distrito: "TUCUME"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "NUEVA ARICA"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "ETEN"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "SANTA ROSA"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "CHICLAYO"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "CHONGOYAPE"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "OYOTUN"},
  { departamento:"LAMBAYEQUE", provincia: "CHICLAYO", distrito: "TUMAN"},
  { departamento:"LAMBAYEQUE", provincia: "FERREÑAFE", distrito: "PITIPO"},
  { departamento:"LAMBAYEQUE", provincia: "LAMBAYEQUE", distrito: "JAYANCA"},
  { departamento:"LAMBAYEQUE", provincia: "LAMBAYEQUE", distrito: "MOTUPE"},
  { departamento:"LAMBAYEQUE", provincia: "LAMBAYEQUE", distrito: "OLMOS"},
  { departamento:"LAMBAYEQUE", provincia: "LAMBAYEQUE", distrito: "ILLIMO"},
  { departamento:"LAMBAYEQUE", provincia: "LAMBAYEQUE", distrito: "PACORA"},
  { departamento:"LAMBAYEQUE", provincia: "LAMBAYEQUE", distrito: "SALAS"},
  { departamento:"PIURA", provincia: "MORROPON", distrito: "BUENOS AIRES"},
  { departamento:"PIURA", provincia: "HUANCABAMBA", distrito: "LALAQUIZ"},
  { departamento:"PIURA", provincia: "MORROPON", distrito: "MORROPON"},
  { departamento:"PIURA", provincia: "MORROPON", distrito: "YAMANGO"},
  { departamento:"PIURA", provincia: "MORROPON", distrito: "CHULUCANAS"},
  { departamento:"PIURA", provincia: "PIURA", distrito: "CASTILLA"},
  { departamento:"PIURA", provincia: "PAITA", distrito: "PAITA"},
  { departamento:"PIURA", provincia: "AYABACA", distrito: "SAPILLICA"},
  { departamento:"PIURA", provincia: "SULLANA", distrito: "QUERECOTILLO"},
  { departamento:"PIURA", provincia: "AYABACA", distrito: "JILILI"},
  { departamento:"PIURA", provincia: "AYABACA", distrito: "SICCHEZ"},
  { departamento:"PIURA", provincia: "TALARA", distrito: "EL ALTO"},
  { departamento:"PIURA", provincia: "PIURA", distrito: "VEINTISEIS DE OCTUBRE"},
  { departamento:"PIURA", provincia: "PAITA", distrito: "VICHAYAL"},
  { departamento:"PIURA", provincia: "HUANCABAMBA", distrito: "HUARMACA"},
  { departamento:"PIURA", provincia: "SECHURA", distrito: "CRISTO NOS VALGA"},
  { departamento:"PIURA", provincia: "SECHURA", distrito: "RINCONADA LLICUAR"},
  { departamento:"PIURA", provincia: "SECHURA", distrito: "BELLAVISTA DE LA UNION"},
  { departamento:"PIURA", provincia: "HUANCABAMBA", distrito: "SAN MIGUEL DE EL FAIQUE"},
  { departamento:"PIURA", provincia: "MORROPON", distrito: "SALITRAL"},
  { departamento:"PIURA", provincia: "SECHURA", distrito: "VICE"},
  { departamento:"PIURA", provincia: "MORROPON", distrito: "SAN JUAN DE BIGOTE"},
  { departamento:"PIURA", provincia: "PAITA", distrito: "ARENAL"},
  { departamento:"PIURA", provincia: "MORROPON", distrito: "SANTA CATALINA DE MOSSA"},
  { departamento:"PIURA", provincia: "MORROPON", distrito: "CHALACO"},
  { departamento:"PIURA", provincia: "PAITA", distrito: "COLAN"},
  { departamento:"PIURA", provincia: "PAITA", distrito: "TAMARINDO"},
  { departamento:"PIURA", provincia: "AYABACA", distrito: "PAIMAS"},
  { departamento:"PIURA", provincia: "AYABACA", distrito: "MONTERO"},
  { departamento:"PIURA", provincia: "TALARA", distrito: "LA BREA"},
  { departamento:"PIURA", provincia: "SULLANA", distrito: "LANCONES"},
  { departamento:"PIURA", provincia: "TALARA", distrito: "LOS ORGANOS"},
  { departamento:"PIURA", provincia: "SULLANA", distrito: "BELLAVISTA"},
  { departamento:"PIURA", provincia: "SULLANA", distrito: "SALITRAL"},
  { departamento:"PIURA", provincia: "SECHURA", distrito: "SECHURA"},
  { departamento:"PIURA", provincia: "PIURA", distrito: "CATACAOS"},
  { departamento:"PIURA", provincia: "AYABACA", distrito: "SUYO"},
  { departamento:"PIURA", provincia: "PIURA", distrito: "PIURA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "LIMA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "MIRAFLORES"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "MAGDALENA DEL MAR"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SAN LUIS"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SANTA ANITA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SURQUILLO"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "BREÑA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SANTA ROSA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SAN JUAN DE MIRAFLORES"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SANTIAGO DE SURCO"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "VILLA EL SALVADOR"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "EL AGUSTINO"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "LOS OLIVOS"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "CARABAYLLO"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "PUCUSANA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "PUNTA NEGRA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "LURIGANCHO"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SAN BORJA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SAN MIGUEL"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "RIMAC"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "INDEPENDENCIA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SAN ISIDRO"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "BARRANCO"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "PUENTE PIEDRA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SAN MARTIN DE PORRES"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "COMAS"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "LA MOLINA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "PACHACAMAC"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "PUNTA HERMOSA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SANTA MARIA DEL MAR"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SAN BARTOLO"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "JESUS MARIA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "LINCE"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "PUEBLO LIBRE"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SAN JUAN DE LURIGANCHO"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "LA VICTORIA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "ANCON"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "ATE"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "CHACLACAYO"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "VILLA MARIA DEL TRIUNFO"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "CIENEGUILLA"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "LURIN"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "CHORRILLOS"},
  { departamento:"LIMA", provincia: "LIMA", distrito: "SANTA MARIA DE HUACHIPA /1"},
];
